In [2]:
import json
import pandas as pd

In [ ]:
file_path = 'api_data_files/international_box_player_season.json'
with open(file_path, 'r') as f:
    json_data = json.load(f)
inter_box = pd.read_json(file_path)
nba_box = pd.read_json('api_data_files/nba_box_player_season.json')
player = pd.read_json('api_data_files/player.json')

In [27]:
# inter_box.info()
inter_box['first_name'] = inter_box['first_name'].str.title()
inter_box['last_name'] = inter_box['last_name'].str.title()
inter_box

,first_name,last_name,season,season_type,league,team,games,starts,minutes,points,...,total_rebounding_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,internal_box_plus_minus,first_name_norm,last_name_norm,full_name_norm,in_nba
0,Theo,Greene,2021,Full Season,EuroLeague,Redhawks,25,18,527.61,195,...,9.7267,19.0212,1.8221,0.0000,13.5671,0.7786,theo,greene,theo|greene,False
1,Theo,Greene,2021,Full Season,Spain - ACB,Redhawks,17,10,356.70,135,...,9.9234,14.7139,0.8723,0.8292,11.1323,2.7367,theo,greene,theo|greene,False
2,Miles,Brussino,2021,Full Season,EuroCup,Orange,12,2,204.70,82,...,10.4102,5.2539,1.5268,3.0675,13.9509,3.2200,miles,brussino,miles|brussino,False
3,Miles,Brussino,2021,Full Season,Italy - Liga A,Orange,16,3,266.00,83,...,8.9342,4.4051,1.9879,1.4668,7.8160,-1.5619,miles,brussino,miles|brussino,False
4,Kadoshnikov,Christmas,2012,Full Season,EuroLeague,Redbirds,6,1,70.48,15,...,6.6163,5.7849,1.8662,2.4437,13.9082,-5.7589,kadoshnikov,christmas,kadoshnikov|christmas,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3365,Mcfarlin,Nowitzki,2021,Full Season,EuroLeague,Buffaloes,23,20,438.10,190,...,16.8587,8.0092,1.4940,4.6382,18.0614,-1.3317,mcfarlin,nowitzki,mcfarlin|nowitzki,True
3366,Deron,Oakley,2021,Full Season,EuroLeague,Buffaloes,10,3,134.96,29,...,8.2733,6.7163,2.3231,0.0000,14.7580,-2.1425,deron,oakley,deron|oakley,False
3367,Jaime,Toolson,2021,Full Season,EuroLeague,Braves,24,1,380.02,131,...,9.7191,11.6266,0.8287,0.6259,17.6622,-0.5522,jaime,toolson,jaime|toolson,False
3368,Visconti,Favors,2021,Full Season,EuroCup,Mastodons,10,5,139.53,52,...,4.0700,3.7897,2.2754,1.3145,12.2893,-3.3007,visconti,favors,visconti|favors,False
3369,Jerryd,Bibby,2021,Full Season,Spain - ACB,Huskies,19,18,381.94,173,...,6.6621,4.3371,1.5731,0.8202,10.7856,-4.9575,jerryd,bibby,jerryd|bibby,False

In [28]:
# nba_box.info()
nba_box['first_name'] = nba_box['first_name'].str.title()
nba_box['last_name'] = nba_box['last_name'].str.title()
nba_box

,first_name,last_name,season,season_type,league,team,games,starts,minutes,points,...,defensive_rebounding_percentage,total_rebounding_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,internal_box_plus_minus,first_name_norm,last_name_norm,full_name_norm
0,Kadoshnikov,Christmas,2017,Full Season,NBA,Thunder,73,6,1135.2833,430,...,8.3138,4.1831,7.9835,1.7237,0.6262,7.8512,-1.8309,kadoshnikov,christmas,kadoshnikov|christmas
1,Kadoshnikov,Christmas,2018,Full Season,NBA,Thunder,81,8,1243.8000,377,...,10.2934,6.3177,5.7126,1.7110,1.1719,7.2601,-1.3166,kadoshnikov,christmas,kadoshnikov|christmas
2,Kadoshnikov,Christmas,2019,Full Season,NBA,Thunder,31,2,588.1667,165,...,7.2142,4.8119,3.7177,1.5495,1.2268,7.9221,-3.1117,kadoshnikov,christmas,kadoshnikov|christmas
3,Kurucs,Humphrey,2013,Full Season,NBA,Raptors,29,0,342.3500,116,...,18.4324,14.6673,6.3495,2.0357,3.8387,15.6365,0.0371,kurucs,humphrey,kurucs|humphrey
4,Kurucs,Humphrey,2014,Full Season,NBA,NaN,63,0,847.7000,171,...,18.4784,14.5251,4.4947,1.5469,2.8704,15.6001,-1.7587,kurucs,humphrey,kurucs|humphrey
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1680,N'Doye,Nwaelele,2017,Full Season,NBA,Bulls,50,18,979.4333,284,...,14.0662,9.1827,4.4250,0.9217,1.7990,14.5908,-4.3281,n'doye,nwaelele,n'doye|nwaelele
1681,N'Doye,Nwaelele,2018,Full Season,NBA,Bulls,54,12,823.8167,218,...,16.4964,9.3931,10.7280,1.0850,1.9314,14.9306,-6.1027,n'doye,nwaelele,n'doye|nwaelele
1682,Mcfarlin,Nowitzki,2018,Full Season,NBA,Cavaliers,40,2,236.9833,132,...,21.3207,16.4043,5.2298,0.5004,4.8256,12.3340,0.4038,mcfarlin,nowitzki,mcfarlin|nowitzki
1683,Mcfarlin,Nowitzki,2019,Full Season,NBA,Cavaliers,59,25,1082.0167,459,...,21.4694,17.3244,8.9796,0.7295,2.2491,13.5531,-3.1735,mcfarlin,nowitzki,mcfarlin|nowitzki
1684,Mcfarlin,Nowitzki,2020,Full Season,NBA,Cavaliers,22,0,220.5833,96,...,25.0595,16.0414,6.3944,1.4132,1.9929,11.0668,-2.9672,mcfarlin,nowitzki,mcfarlin|nowitzki

In [20]:
player.head()
player['first_name'] = player['first_name'].str.title()
player['last_name'] = player['last_name'].str.title()
player.head()

    first_name  last_name  birth_date
0         Theo     Greene  1995-12-26
1        Miles   Brussino  1993-02-01
2        Ayres  Bortolani  1969-01-20
3  Kadoshnikov  Christmas  1993-08-10
4      Rashawn         De  1989-08-30

In [35]:
combined = pd.concat([inter_box, nba_box])
combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5055 entries, 0 to 1684
Data columns (total 59 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   first_name                       5055 non-null   object
 1   last_name                        5055 non-null   object
 2   season                           5055 non-null   int64
 3   season_type                      5055 non-null   object
 4   league                           5055 non-null   object
 5   team                             4789 non-null   object
 6   games                            5055 non-null   int64
 7   starts                           5055 non-null   int64
 8   minutes                          5055 non-null   float64
 9   points                           5055 non-null   int64
 10  two_points_made                  5055 non-null   int64
 11  two_points_attempted             5055 non-null   int64
 12  three_points_made                5055 non-null   int64
 13  three_points_attempted           5055 non-null   int64
 14  free_throws_made                 5055 non-null   int64
 15  free_throws_attempted            5055 non-null   int64
 16  blocked_shot_attempts            5055 non-null   int64
 17  offensive_rebounds               5055 non-null   int64
 18  defensive_rebounds               5055 non-null   int64
 19  assists                          5055 non-null   int64
 20  screen_assists                   5055 non-null   int64
 21  turnovers                        5055 non-null   int64
 22  steals                           5055 non-null   int64
 23  deflections                      5055 non-null   int64
 24  loose_balls_recovered            5055 non-null   int64
 25  blocked_shots                    5055 non-null   int64
 26  personal_fouls                   5055 non-null   int64
 27  personal_fouls_drawn             5055 non-null   int64
 28  offensive_fouls                  5055 non-null   int64
 29  charges_drawn                    5055 non-null   int64
 30  technical_fouls                  5055 non-null   int64
 31  flagrant_fouls                   5055 non-null   int64
 32  ejections                        5055 non-null   int64
 33  points_off_turnovers             5055 non-null   int64
 34  points_in_paint                  5055 non-null   int64
 35  second_chance_points             5055 non-null   int64
 36  fast_break_points                5055 non-null   int64
 37  possessions                      5055 non-null   float64
 38  estimated_possessions            5055 non-null   float64
 39  team_possessions                 5055 non-null   float64
 40  usage_percentage                 5055 non-null   float64
 41  true_shooting_percentage         5002 non-null   float64
 42  three_point_attempt_rate         4995 non-null   float64
 43  free_throw_rate                  4995 non-null   float64
 44  offensive_rebounding_percentage  5055 non-null   float64
 45  defensive_rebounding_percentage  5055 non-null   float64
 46  total_rebounding_percentage      5055 non-null   float64
 47  assist_percentage                5055 non-null   float64
 48  steal_percentage                 5055 non-null   float64
 49  block_percentage                 5055 non-null   float64
 50  turnover_percentage              5013 non-null   float64
 51  internal_box_plus_minus          4998 non-null   float64
 52  first_name_norm                  5055 non-null   object
 53  last_name_norm                   5055 non-null   object
 54  full_name_norm                   5055 non-null   object
 55  in_nba                           3370 non-null   object
 56  plus_minus                       1685 non-null   float64
 57  calculated_possessions           1682 non-null   float64
 58  plays_used                       1682 non-null   float64
dtypes: float64(19), int64(31), object(9)
memory usage: 2.3+ MB

In [ ]:
# join birth_date to first and last name
# notice capital vs non capital letters
# join data
merged_df = pd.merge(combined, player, on=['first_name', 'last_name'], how='left')
merged_df.info()
merged_df.to_csv('merged.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5213 entries, 0 to 5212
Data columns (total 63 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   first_name                       5213 non-null   object
 1   last_name                        5213 non-null   object
 2   season                           5055 non-null   float64
 3   season_type                      5055 non-null   object
 4   league                           5055 non-null   object
 5   team                             4789 non-null   object
 6   games                            5055 non-null   float64
 7   starts                           5055 non-null   float64
 8   minutes                          5055 non-null   float64
 9   points                           5055 non-null   float64
 10  two_points_made                  5055 non-null   float64
 11  two_points_attempted             5055 non-null   float64
 12  three_points_made                5055 non-null   float64
 13  three_points_attempted           5055 non-null   float64
 14  free_throws_made                 5055 non-null   float64
 15  free_throws_attempted            5055 non-null   float64
 16  blocked_shot_attempts            5055 non-null   float64
 17  offensive_rebounds               5055 non-null   float64
 18  defensive_rebounds               5055 non-null   float64
 19  assists                          5055 non-null   float64
 20  screen_assists                   5055 non-null   float64
 21  turnovers                        5055 non-null   float64
 22  steals                           5055 non-null   float64
 23  deflections                      5055 non-null   float64
 24  loose_balls_recovered            5055 non-null   float64
 25  blocked_shots                    5055 non-null   float64
 26  personal_fouls                   5055 non-null   float64
 27  personal_fouls_drawn             5055 non-null   float64
 28  offensive_fouls                  5055 non-null   float64
 29  charges_drawn                    5055 non-null   float64
 30  technical_fouls                  5055 non-null   float64
 31  flagrant_fouls                   5055 non-null   float64
 32  ejections                        5055 non-null   float64
 33  points_off_turnovers             5055 non-null   float64
 34  points_in_paint                  5055 non-null   float64
 35  second_chance_points             5055 non-null   float64
 36  fast_break_points                5055 non-null   float64
 37  possessions                      5055 non-null   float64
 38  estimated_possessions            5055 non-null   float64
 39  team_possessions                 5055 non-null   float64
 40  usage_percentage                 5055 non-null   float64
 41  true_shooting_percentage         5002 non-null   float64
 42  three_point_attempt_rate         4995 non-null   float64
 43  free_throw_rate                  4995 non-null   float64
 44  offensive_rebounding_percentage  5055 non-null   float64
 45  defensive_rebounding_percentage  5055 non-null   float64
 46  total_rebounding_percentage      5055 non-null   float64
 47  assist_percentage                5055 non-null   float64
 48  steal_percentage                 5055 non-null   float64
 49  block_percentage                 5055 non-null   float64
 50  turnover_percentage              5013 non-null   float64
 51  internal_box_plus_minus          4998 non-null   float64
 52  first_name_norm_x                5055 non-null   object
 53  last_name_norm_x                 5055 non-null   object
 54  full_name_norm_x                 5055 non-null   object
 55  in_nba                           3370 non-null   object
 56  plus_minus                       1685 non-null   float64
 57  calculated_possessions           1682 non-null   float64
 58  plays_used                       1682 non-null   float64
 59  birth_date                       5021 non-null   object
 60  first_name_norm_y                5021 non-null   object
 61  last_name_norm_y                 5021 non-null   object
 62  full_name_norm_y                 5021 non-null   object
dtypes: float64(50), object(13)
memory usage: 2.5+ MB

In [24]:
# normalize first/last names into a single key to reduce mismatches
for df in [inter_box, nba_box, player]:
    df['first_name_norm'] = df['first_name'].astype(str).str.strip().str.lower()
    df['last_name_norm']  = df['last_name'].astype(str).str.strip().str.lower()
    df['full_name_norm']  = df['first_name_norm'] + '|' + df['last_name_norm']  # safe composite key

In [25]:
# boolean mask per row, then counts
inter_box['in_nba'] = inter_box['full_name_norm'].isin(nba_box['full_name_norm'])
inter_box['in_nba'].value_counts(dropna=False)   # shows how many True/False/NaN
inter_box['in_nba'].sum()                        # number of rows in inter_box that match nba_box
len(inter_box)                                   # total rows in inter_box

3370

In [26]:
inter_names = set(inter_box['full_name_norm'].dropna().unique())
nba_names   = set(nba_box['full_name_norm'].dropna().unique())
player_names= set(player['full_name_norm'].dropna().unique())

common_inter_nba = inter_names & nba_names
len(common_inter_nba), "unique full names in both inter_box and nba_box"

# also for all three:
common_all_three = inter_names & nba_names & player_names
len(common_all_three), "unique full names present in all three datasets"

(433, 'unique full names present in all three datasets')