## Overview
In this jupyter notebook, I web scrape and data cleane for NBA team statistics. The focus is on standardizing column names and preparing the data for analysis.

In a previous version, I read in data using the urls directly. Now, I have saved the data as CSV files locally and read them in from there for better reliability.

In [87]:
import pandas as pd

In [102]:
kings_pergame = pd.read_csv('basketball_reference/2425_kings_pergame.csv')
kings_advanced = pd.read_csv('basketball_reference/2425_kings_advanced.csv')

league_pergame = pd.read_csv('basketball_reference/2425_league_pergame.csv')
league_advanced = pd.read_csv('basketball_reference/2425_league_advanced.csv')

In [89]:
# kings_pergame.columns
# Index(['Player', 'Age', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
#        '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
#        'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
#       dtype='object')
# kings_advanced.columns
# Index(['Player', 'Age', 'Pos', 'G', 'GS', 'MP', 'PER', 'TS%', '3PAr', 'FTr',
#        'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS',
#        'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP'],
#       dtype='object')
# league_pergame.columns
# Index(['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P',
#        '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
#        'BLK', 'TOV', 'PF', 'PTS'],
#       dtype='object')
# league_advanced.columns
# Index(['Rk', 'Team', 'Age', 'W', 'L', 'PW', 'PL', 'MOV', 'SOS', 'SRS', 'ORtg',
#        'DRtg', 'NRtg', 'Pace', 'FTr', '3PAr', 'TS%', 'Offense_eFG%',
#        'Offense_TOV%', 'Offense_ORB%', 'Offense_FT/FGA', 'Defense_eFG%',
#        'Defense_TOV%', 'Defense_DRB%', 'Defense_FT/FGA', 'Arena', 'Attend.',
#        'Attend./G'],
#       dtype='object')

In [90]:
# --------------------------------------------------------------
# 2. Standardize column names (lower, _, pct)
# --------------------------------------------------------------
def clean_cols(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace('%', '_pct', regex=False)
        .str.replace('/', '_', regex=False)
        .str.replace(' ', '_', regex=False)
    )
    return df

kings_pergame = clean_cols(kings_pergame)
kings_advanced = clean_cols(kings_advanced)
league_pergame = clean_cols(league_pergame)
league_advanced = clean_cols(league_advanced)

# KINGS: 'player' for both
kings_pergame = kings_pergame.rename(columns={'player': 'player'})
kings_advanced = kings_advanced.rename(columns={'player': 'player'})

# LEAGUE: 'team' for both (no player in league)
league_pergame = league_pergame.rename(columns={'team': 'team'})
league_advanced = league_advanced.rename(columns={'team': 'team'})

#merge kings
# Drop duplicates from advanced (age, pos, g, gs, mp exist in both)
dup_cols = ['age', 'pos', 'g', 'gs', 'mp']
kings_advanced = kings_advanced.drop(columns=[c for c in dup_cols if c in kings_advanced.columns])

# Unique advanced cols to add
kings_adv_unique = [c for c in kings_advanced.columns if c not in kings_pergame.columns]

kings_merged = kings_pergame.merge(
    kings_advanced[['player'] + kings_adv_unique],
    on='player',
    how='left'
)

# Remove any team totals row if slipped in
kings_merged = kings_merged[~kings_merged['player'].str.contains('Total|Team', na=False)]

print(f"KINGS MERGED: {kings_merged.shape[0]} players, {kings_merged.shape[1]} cols")
print("Kings columns:", kings_merged.columns.tolist())

#merge league
league_adv_unique = [c for c in league_advanced.columns if c not in league_pergame.columns]

league_teams = league_pergame.merge(
    league_advanced[['team'] + league_adv_unique],
    on='team',
    how='left'
)

KINGS MERGED: 20 players, 48 cols
Kings columns: ['player', 'age', 'pos', 'g', 'gs', 'mp', 'fg', 'fga', 'fg_pct', '3p', '3pa', '3p_pct', '2p', '2pa', '2p_pct', 'efg_pct', 'ft', 'fta', 'ft_pct', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'per', 'ts_pct', '3par', 'ftr', 'orb_pct', 'drb_pct', 'trb_pct', 'ast_pct', 'stl_pct', 'blk_pct', 'tov_pct', 'usg_pct', 'ows', 'dws', 'ws', 'ws_48', 'obpm', 'dbpm', 'bpm', 'vorp']

In [91]:
print("\n=== KINGS PLAYER SAMPLE ===")
display(kings_merged.head(3))

print("\n=== LEAGUE TEAM SAMPLE (e.g., Kings) ===")
display(league_teams[league_teams['team'].str.contains('Sacramento Kings', case=False)].T)

print("\nBPM now in Kings roster:")
display(kings_merged[['player', 'bpm', 'obpm', 'dbpm', 'vorp']].head())

=== KINGS PLAYER SAMPLE ===

,player,age,pos,g,gs,mp,fg,fga,fg_pct,3p,...,tov_pct,usg_pct,ows,dws,ws,ws_48,obpm,dbpm,bpm,vorp
0,De'Aaron Fox,26,PG,74,74,35.9,9.7,20.9,0.465,2.9,...,10.1,31.0,3.3,3.2,6.5,0.117,2.6,0.1,2.7,3.2
1,Domantas Sabonis,27,C,82,82,35.7,7.7,13.0,0.594,0.4,...,17.9,22.2,8.6,4.0,12.6,0.206,4.0,2.4,6.5,6.2
2,Keegan Murray,23,SF,77,77,33.6,5.8,12.7,0.454,2.4,...,5.9,18.1,2.6,2.6,5.2,0.096,-0.4,-0.5,-0.9,0.8

=== LEAGUE TEAM SAMPLE (e.g., Kings) ===

                                9
rk                             10
team             Sacramento Kings
g                              82
mp                          242.4
fg                           43.0
fga                          90.1
fg_pct                      0.478
3p                           12.6
3pa                          35.2
3p_pct                      0.357
2p                           30.5
2pa                          54.9
2p_pct                      0.555
ft                           17.1
fta                          21.2
ft_pct                      0.806
orb                          11.0
drb                          33.2
trb                          44.2
ast                          26.5
stl                           7.6
blk                           4.4
tov                          13.3
pf                           18.9
pts                         115.7
age                          27.8
w                              40
l                              42
pw                             42
pl                             40
mov                          0.48
sos                          0.11
srs                          0.58
ortg                        116.7
drtg                        116.2
nrtg                          0.5
pace                         98.2
ftr                         0.235
3par                        0.391
ts_pct                      0.582
offense_efg_pct             0.548
offense_tov_pct              11.8
offense_orb_pct              25.4
offense_ft_fga               0.19
defense_efg_pct             0.557
defense_tov_pct              12.5
defense_drb_pct              76.9
defense_ft_fga                0.2
arena             Golden 1 Center
attend.                   696,409
attend._g                  16,986

BPM now in Kings roster:

             player  bpm  obpm  dbpm  vorp
0      De'Aaron Fox  2.7   2.6   0.1   3.2
1  Domantas Sabonis  6.5   4.0   2.4   6.2
2     Keegan Murray -0.9  -0.4  -0.5   0.8
3   Harrison Barnes -1.8  -0.6  -1.2   0.1
4        Malik Monk  0.6   1.5  -1.0   1.2

In [92]:
league_teams['team'] = league_teams['team'].astype(str).str.replace('*', '', regex=False)
league_teams

,rk,team,g,mp,fg,fga,fg_pct,3p,3pa,3p_pct,...,offense_tov_pct,offense_orb_pct,offense_ft_fga,defense_efg_pct,defense_tov_pct,defense_drb_pct,defense_ft_fga,arena,attend.,attend._g
0,1,Cleveland Cavaliers,82,240.9,44.5,90.8,0.491,15.9,41.5,0.383,...,11.6,25.9,0.187,0.528,12.6,74.8,0.181,Rocket Arena,"796,712","19,432"
1,2,Memphis Grizzlies,82,240.3,44.8,93.3,0.479,13.9,37.9,0.367,...,13.1,28.7,0.196,0.533,12.9,74.9,0.206,FedEx Forum,"683,067","16,660"
2,3,Denver Nuggets,82,242.1,45.4,89.8,0.506,12.0,31.9,0.376,...,12.5,26.7,0.200,0.542,11.3,74.6,0.173,Ball Arena,"811,211","19,786"
3,4,Oklahoma City Thunder,82,240.3,44.6,92.7,0.482,14.5,38.8,0.374,...,10.3,24.2,0.180,0.513,14.9,74.6,0.211,Paycom Center,"754,832","17,973"
4,5,Atlanta Hawks,82,241.2,43.4,91.8,0.472,13.5,37.7,0.358,...,13.2,26.3,0.196,0.560,13.8,76.0,0.202,State Farm Arena,"657,613","16,440"
5,6,Chicago Bulls,82,240.9,43.2,92.0,0.470,15.4,42.0,0.367,...,12.7,22.3,0.173,0.539,10.8,76.6,0.178,United Center,"825,659","20,138"
6,7,Indiana Pacers,82,242.1,43.6,89.3,0.488,13.2,35.8,0.368,...,11.8,21.3,0.190,0.546,13.1,74.5,0.190,Gainbridge Fieldhouse,"685,434","16,737"
7,8,Boston Celtics,82,241.8,41.6,90.0,0.462,17.8,48.2,0.368,...,10.8,25.7,0.169,0.522,11.6,76.0,0.154,TD Garden,"785,396","19,156"
8,9,New York Knicks,82,242.4,43.3,89.2,0.486,12.6,34.1,0.369,...,11.9,26.0,0.186,0.549,13.1,74.5,0.176,Madison Square Garden (IV),"811,794","19,800"
9,10,Sacramento Kings,82,242.4,43.0,90.1,0.478,12.6,35.2,0.357,...,11.8,25.4,0.190,0.557,12.5,76.9,0.200,Golden 1 Center,"696,409","16,986"
10,11,Milwaukee Bucks,82,240.9,42.0,86.4,0.486,14.2,36.6,0.387,...,12.2,19.3,0.201,0.533,11.4,76.2,0.174,Fiserv Forum,"732,014","17,437"
11,12,Detroit Pistons,82,241.5,42.7,89.8,0.476,12.8,35.4,0.362,...,13.0,26.2,0.192,0.539,13.3,76.0,0.214,Little Caesars Arena,"781,929","19,071"
12,13,Minnesota Timberwolves,82,241.8,41.0,87.6,0.468,15.0,39.9,0.377,...,13.0,25.8,0.196,0.532,13.2,75.1,0.178,Target Center,"772,249","18,835"
13,14,Houston Rockets,82,241.2,42.5,93.4,0.455,12.7,35.8,0.353,...,11.8,31.7,0.178,0.528,12.8,76.2,0.186,Toyota Center,"716,853","17,484"
14,15,Dallas Mavericks,82,240.6,42.0,87.7,0.479,12.4,34.2,0.364,...,12.5,23.3,0.203,0.540,11.6,73.1,0.179,American Airlines Center,"803,174","20,079"
15,16,San Antonio Spurs,82,240.6,41.8,89.8,0.465,14.1,39.6,0.357,...,12.3,24.3,0.181,0.551,12.0,73.0,0.158,Frost Bank Center,"731,474","17,976"
16,17,Golden State Warriors,82,240.6,40.8,90.4,0.451,15.4,42.4,0.364,...,12.3,27.3,0.187,0.541,14.1,75.6,0.189,Chase Center,"740,624","18,064"
17,18,Phoenix Suns,82,241.8,41.2,86.3,0.478,14.3,38.0,0.378,...,12.8,22.6,0.195,0.552,10.9,74.1,0.191,Footprint Center,"699,911","17,071"
18,19,Los Angeles Lakers,82,240.6,40.9,85.5,0.479,13.3,36.4,0.366,...,12.7,23.3,0.213,0.539,12.2,74.5,0.178,Crypto.com Arena,"767,626","18,723"
19,20,Los Angeles Clippers,82,241.5,41.6,86.3,0.482,12.5,33.4,0.373,...,13.4,24.4,0.200,0.536,13.7,77.5,0.189,Intuit Dome,"679,593","16,575"
20,21,Utah Jazz,82,241.5,40.3,88.7,0.454,14.0,39.8,0.350,...,14.9,26.9,0.195,0.559,10.3,74.1,0.185,Delta Center,"745,175","18,175"
21,22,Toronto Raptors,82,241.5,41.6,91.0,0.458,11.8,34.0,0.348,...,13.3,27.3,0.173,0.541,13.2,73.9,0.222,Scotiabank Arena,"768,573","18,746"
22,23,Portland Trail Blazers,82,241.2,40.5,90.2,0.450,12.9,37.7,0.342,...,13.8,29.2,0.187,0.543,13.6,72.5,0.204,Moda Center,"719,369","17,546"
23,24,Miami Heat,82,243.0,40.5,87.0,0.465,13.7,37.3,0.367,...,12.4,22.3,0.183,0.543,12.5,75.8,0.157,Kaseya Center,"808,337","19,716"
24,25,New Orleans Pelicans,82,240.9,40.6,89.9,0.452,12.0,34.6,0.347,...,12.8,26.3,0.184,0.564,12.3,72.7,0.190,Smoothie King Center,"689,400","16,815"
25,26,Philadelphia 76ers,82,241.5,39.7,87.4,0.454,12.7,37.2,0.341,...,12.3,23.4,0.201,0.570,14.3,71.8,0.194,Wells Fargo Center,"813,621","19,844"
26,27,Washington Wizards,82,240.6,39.4,89.9,0.439,13.1,39.1,0.335,...,13.6,22.7,0.178,0.548,11.4,71.9,0.202,Capital One Arena,"663,691","16,084"
27,28,Orlando Magic,82,240.6,38.2,85.8,0.445,11.2,35.3,0.318,...,12.9,25.3,0.208,0.538,15.0,77.0,0.220,Kia Center,"762,121","18,588"
28,29,Charlotte Hornets,82,240.9,38.3,89.1,0.430,13.0,38.3,0.339,...,13.7,26.5,0.174,0.547,11.9,74.5,0.190,Spectrum Center,"703,935","17,169"
29,30,Brooklyn Nets,82,241.2,37.6,86.1,0.437,13.6,39.4,0.344,...,13.7,24.5,0.189,0.557,13.7,75.0,0.218,Barclays Center,"713,304","17,398"

In [93]:
# Example metrics list now matches the DataFrame
metrics = ['fg', '3p', 'ft', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pts']
league_teams.columns

Index(['rk', 'team', 'g', 'mp', 'fg', 'fga', 'fg_pct', '3p', '3pa', '3p_pct',
       '2p', '2pa', '2p_pct', 'ft', 'fta', 'ft_pct', 'orb', 'drb', 'trb',
       'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'age', 'w', 'l', 'pw', 'pl',
       'mov', 'sos', 'srs', 'ortg', 'drtg', 'nrtg', 'pace', 'ftr', '3par',
       'ts_pct', 'offense_efg_pct', 'offense_tov_pct', 'offense_orb_pct',
       'offense_ft_fga', 'defense_efg_pct', 'defense_tov_pct',
       'defense_drb_pct', 'defense_ft_fga', 'arena', 'attend.', 'attend._g'],
      dtype='object')

In [94]:
# Find Sacramento Kings row in league table
kings_team_stats = league_teams[league_teams['team'].str.contains("Sacramento Kings", case=False, na=False)].iloc[0]
kings_team_stats

rk                               10
team               Sacramento Kings
g                                82
mp                            242.4
fg                             43.0
fga                            90.1
fg_pct                        0.478
3p                             12.6
3pa                            35.2
3p_pct                        0.357
2p                             30.5
2pa                            54.9
2p_pct                        0.555
ft                             17.1
fta                            21.2
ft_pct                        0.806
orb                            11.0
drb                            33.2
trb                            44.2
ast                            26.5
stl                             7.6
blk                             4.4
tov                            13.3
pf                             18.9
pts                           115.7
age                            27.8
w                                40
l                                42
pw                               42
pl                               40
mov                            0.48
sos                            0.11
srs                            0.58
ortg                          116.7
drtg                          116.2
nrtg                            0.5
pace                           98.2
ftr                           0.235
3par                          0.391
ts_pct                        0.582
offense_efg_pct               0.548
offense_tov_pct                11.8
offense_orb_pct                25.4
offense_ft_fga                 0.19
defense_efg_pct               0.557
defense_tov_pct                12.5
defense_drb_pct                76.9
defense_ft_fga                  0.2
arena               Golden 1 Center
attend.                     696,409
attend._g                    16,986
Name: 9, dtype: object

In [95]:
league_means = league_teams[metrics].mean(numeric_only=True)
league_means

fg      41.686667
3p      13.536667
ft      16.903333
orb     11.123333
drb     32.986667
trb     44.113333
ast     26.546667
stl      8.210000
blk      4.883333
tov     14.306667
pts    113.826667
dtype: float64

In [96]:
# Combine Kings stats and league averages into one DataFrame
comparison = pd.DataFrame({
    'league_avg': league_means,
    'kings': kings_team_stats[league_means.index]  # make sure order matches
})

# Compute differences
comparison['difference'] = comparison['kings'] - comparison['league_avg']

# For metrics where higher is bad (like turnovers), invert the difference
inverse_metrics = ['tov']  # higher turnovers = weakness
comparison['score'] = comparison.apply(
    lambda row: -row['difference'] if row.name not in inverse_metrics else row['difference'],
    axis=1
)

# Normalize to sum to 1 (absolute values)
total = comparison['score'].abs().sum()
comparison['weight'] = (comparison['score'] / total).round(3)

print("\n--- Needs Profile ---\n")
print(comparison[['kings', 'league_avg', 'difference', 'weight']])

--- Needs Profile ---

     kings  league_avg difference  weight
fg    43.0   41.686667   1.313333  -0.191
3p    12.6   13.536667  -0.936667   0.136
ft    17.1   16.903333   0.196667  -0.029
orb   11.0   11.123333  -0.123333   0.018
drb   33.2   32.986667   0.213333  -0.031
trb   44.2   44.113333   0.086667  -0.013
ast   26.5   26.546667  -0.046667   0.007
stl    7.6    8.210000      -0.61   0.089
blk    4.4    4.883333  -0.483333   0.070
tov   13.3   14.306667  -1.006667  -0.146
pts  115.7  113.826667   1.873333  -0.272

In [97]:
league_teams.drop(columns=['arena', 'attend.', 'attend._g'], inplace=True)
league_teams
# kings_merged

,rk,team,g,mp,fg,fga,fg_pct,3p,3pa,3p_pct,...,3par,ts_pct,offense_efg_pct,offense_tov_pct,offense_orb_pct,offense_ft_fga,defense_efg_pct,defense_tov_pct,defense_drb_pct,defense_ft_fga
0,1,Cleveland Cavaliers,82,240.9,44.5,90.8,0.491,15.9,41.5,0.383,...,0.457,0.607,0.578,11.6,25.9,0.187,0.528,12.6,74.8,0.181
1,2,Memphis Grizzlies,82,240.3,44.8,93.3,0.479,13.9,37.9,0.367,...,0.406,0.588,0.554,13.1,28.7,0.196,0.533,12.9,74.9,0.206
2,3,Denver Nuggets,82,242.1,45.4,89.8,0.506,12.0,31.9,0.376,...,0.356,0.604,0.573,12.5,26.7,0.200,0.542,11.3,74.6,0.173
3,4,Oklahoma City Thunder,82,240.3,44.6,92.7,0.482,14.5,38.8,0.374,...,0.419,0.593,0.560,10.3,24.2,0.180,0.513,14.9,74.6,0.211
4,5,Atlanta Hawks,82,241.2,43.4,91.8,0.472,13.5,37.7,0.358,...,0.410,0.579,0.546,13.2,26.3,0.196,0.560,13.8,76.0,0.202
5,6,Chicago Bulls,82,240.9,43.2,92.0,0.470,15.4,42.0,0.367,...,0.457,0.585,0.553,12.7,22.3,0.173,0.539,10.8,76.6,0.178
6,7,Indiana Pacers,82,242.1,43.6,89.3,0.488,13.2,35.8,0.368,...,0.400,0.594,0.562,11.8,21.3,0.190,0.546,13.1,74.5,0.190
7,8,Boston Celtics,82,241.8,41.6,90.0,0.462,17.8,48.2,0.368,...,0.536,0.591,0.561,10.8,25.7,0.169,0.522,11.6,76.0,0.154
8,9,New York Knicks,82,242.4,43.3,89.2,0.486,12.6,34.1,0.369,...,0.382,0.589,0.556,11.9,26.0,0.186,0.549,13.1,74.5,0.176
9,10,Sacramento Kings,82,242.4,43.0,90.1,0.478,12.6,35.2,0.357,...,0.391,0.582,0.548,11.8,25.4,0.190,0.557,12.5,76.9,0.200
10,11,Milwaukee Bucks,82,240.9,42.0,86.4,0.486,14.2,36.6,0.387,...,0.424,0.598,0.568,12.2,19.3,0.201,0.533,11.4,76.2,0.174
11,12,Detroit Pistons,82,241.5,42.7,89.8,0.476,12.8,35.4,0.362,...,0.394,0.580,0.547,13.0,26.2,0.192,0.539,13.3,76.0,0.214
12,13,Minnesota Timberwolves,82,241.8,41.0,87.6,0.468,15.0,39.9,0.377,...,0.455,0.588,0.554,13.0,25.8,0.196,0.532,13.2,75.1,0.178
13,14,Houston Rockets,82,241.2,42.5,93.4,0.455,12.7,35.8,0.353,...,0.384,0.553,0.523,11.8,31.7,0.178,0.528,12.8,76.2,0.186
14,15,Dallas Mavericks,82,240.6,42.0,87.7,0.479,12.4,34.2,0.364,...,0.389,0.583,0.549,12.5,23.3,0.203,0.540,11.6,73.1,0.179
15,16,San Antonio Spurs,82,240.6,41.8,89.8,0.465,14.1,39.6,0.357,...,0.441,0.575,0.544,12.3,24.3,0.181,0.551,12.0,73.0,0.158
16,17,Golden State Warriors,82,240.6,40.8,90.4,0.451,15.4,42.4,0.364,...,0.469,0.568,0.536,12.3,27.3,0.187,0.541,14.1,75.6,0.189
17,18,Phoenix Suns,82,241.8,41.2,86.3,0.478,14.3,38.0,0.378,...,0.440,0.595,0.561,12.8,22.6,0.195,0.552,10.9,74.1,0.191
18,19,Los Angeles Lakers,82,240.6,40.9,85.5,0.479,13.3,36.4,0.366,...,0.425,0.593,0.557,12.7,23.3,0.213,0.539,12.2,74.5,0.178
19,20,Los Angeles Clippers,82,241.5,41.6,86.3,0.482,12.5,33.4,0.373,...,0.387,0.589,0.554,13.4,24.4,0.200,0.536,13.7,77.5,0.189
20,21,Utah Jazz,82,241.5,40.3,88.7,0.454,14.0,39.8,0.350,...,0.449,0.568,0.533,14.9,26.9,0.195,0.559,10.3,74.1,0.185
21,22,Toronto Raptors,82,241.5,41.6,91.0,0.458,11.8,34.0,0.348,...,0.373,0.553,0.522,13.3,27.3,0.173,0.541,13.2,73.9,0.222
22,23,Portland Trail Blazers,82,241.2,40.5,90.2,0.450,12.9,37.7,0.342,...,0.418,0.555,0.521,13.8,29.2,0.187,0.543,13.6,72.5,0.204
23,24,Miami Heat,82,243.0,40.5,87.0,0.465,13.7,37.3,0.367,...,0.429,0.576,0.544,12.4,22.3,0.183,0.543,12.5,75.8,0.157
24,25,New Orleans Pelicans,82,240.9,40.6,89.9,0.452,12.0,34.6,0.347,...,0.385,0.552,0.519,12.8,26.3,0.184,0.564,12.3,72.7,0.190
25,26,Philadelphia 76ers,82,241.5,39.7,87.4,0.454,12.7,37.2,0.341,...,0.426,0.563,0.527,12.3,23.4,0.201,0.570,14.3,71.8,0.194
26,27,Washington Wizards,82,240.6,39.4,89.9,0.439,13.1,39.1,0.335,...,0.435,0.546,0.512,13.6,22.7,0.178,0.548,11.4,71.9,0.202
27,28,Orlando Magic,82,240.6,38.2,85.8,0.445,11.2,35.3,0.318,...,0.411,0.550,0.510,12.9,25.3,0.208,0.538,15.0,77.0,0.220
28,29,Charlotte Hornets,82,240.9,38.3,89.1,0.430,13.0,38.3,0.339,...,0.430,0.537,0.503,13.7,26.5,0.174,0.547,11.9,74.5,0.190
29,30,Brooklyn Nets,82,241.2,37.6,86.1,0.437,13.6,39.4,0.344,...,0.458,0.552,0.516,13.7,24.5,0.189,0.557,13.7,75.0,0.218

In [ ]:
kings_merged.to_csv('2425_kings_merged.csv', index=False)
league_teams.to_csv('2425_league_teams_merged.csv', index=False)